export { default as one } from "./1.jpg";
export { default as two } from "./2.jpg";
export { default as three } from "./3.jpg";
export { default as four } from "./4.jpg";
export { default as five } from "./5.jpg";
export { default as six } from "./6.jpg";
export { default as seven } from "./7.jpg";
export { default as favicon } from "./favicon.png";
export { default as og } from "./og.jpg";
