/* eslint-disable */

export const german = {
  "nav.about": "Über uns",
  "nav.portfolio": "Angebot",
  "nav.partners": "Partner",
  "nav.contact": "Kontakt",
  "nav.start": "Start",

  "home.meta.title": "SwissPlant GmbH &ndash; Ihr Spezialist für Gemüsejungpflanzen",
  "home.meta.description": "Die Swissplant GmbH ist Ihr Ansprechpartner für professionellen Gemüseanbau im Berner Seeland. Bei uns bekommen Sie Warmhauspflanzen in verschiedenen Varianten.",
  "home.meta.keywords": "gemüse, gemuese, jungpflanzen, setzlinge, salat, schweiz, seeland, müntschemier, muentschemier, swissplant, agriplant, swissplant gmbh, agriplant ag, anbau, warmhauspflanzen, distro",
  "home.about.heading": "Wer wir sind",
  "home.about.intro": "Die Firma SwissPlant GmbH ist Verkaufsstelle für Gemüsejungpflanzen der Firmen AgriPlant AG Schweiz und Gipmans Holland.",
  "home.portfolio.heading": "Was wir Ihnen bieten",
  "home.portfolio.intro": "Unser Produktionsstandort der Firma AgriPlant AG befindet sich im Berner Seeland. Die zentrale Lage der Firma bietet uns die Möglichkeit Sie schnell und kompetent zu beliefern.",
  "home.partners.heading": "Mit wem wir arbeiten",
  "home.partners.intro": "Die Firma Gipmans aus Holland beliefert uns als Sortimentsergänzung mit Warmhaus- und Speedypflanzen.",
  "home.contact.heading": "Wie Sie uns erreichen",
  "home.contact.intro": "Wir stehen natürlich gerne für allfällige Informationen und Ratschläge zur Verfügung. Egal, ob E-Mail, Telefon oder vor Ort.",
  "home.button.more": "Mehr erfahren",

  "about.meta.title": "SwissPlant GmbH &ndash; Über uns",
  "about.meta.description": "Erfahren Sie mehr über die SwissPlant GmbH und wer überhaupt hinter ihr steckt.",
  "about.meta.keywords": "über uns, anfang, geschichte, müntschemier, martin löffel, erfahrung, gemüsebau, kompetent, muentschemier, swissplant, agriplant, swissplant gmbh, agriplant ag, angestellte, mitarbeiter, geschäftsführung",
  "about.copy.first": "Den Anfang nehmen all diese Gemüse und Salate als Jungpflanzen, die von der Firma AgriPlant AG in Müntschemier angezogen werden. Geschäftsführer unserer Firmen Martin Löffel, fasst den Weg der Keimlinge bis hin zu ausgewachsenen Pflanzen so zusammen: &laquo;Wir stehen als Zulieferbetrieb der Gemüsebaubetriebe am Anfang der Produktionskette und kultivieren die Jungpflanzen, die anschliessend von den Gemüsegärtnern gepflanzt werden.&raquo;",
  "about.copy.second": "Die Handelsfirma SwissPlant GmbH, bietet Ihnen Gemüsejungpflanzen in allen möglichen Variationen und Grössen an. Durch unsere jahrelange Erfahrung im Gemüsebau können wir Ihnen eine kompetente und fachspezifische Beratung für unsere klimatischen Bedingungen garantieren. <a href=\"./angebot.html\">Unser Sortiment</a> ist eine Zusammenstellung aus verschiedenen Züchtungsprogrammen der weltweit tätigen Anbieter von Hochleistungssaatgut.",
  "about.copy.third": "Zu unseren Zulieferfirmen im Bereich Saatgut gehören: <a href=\"http://bejosamen.de\" target=\"_blank\">Bejo</a>, <a href=\"http://enzazaden.de\" target=\"_blank\">Enza</a>, <a href=\"http://rijkzwaan.de\" target=\"_blank\">Rijk Zwaan</a>, <a href=\"http://hildsamen.de/ueber_uns.htm\" target=\"_blank\">Hild</a>, <a href=\"http://syngenta.ch\" target=\"_blank\">Syngenta</a> und <a href=\"http://www.sakata.com\" target=\"_blank\">Sakata</a>. Unsere Anzuchterde beziehen wir bei den Firmen <a href=\"http://floragard.de\" target=\"_blank\">Floragard</a> und <a href=\"http://klasmann-deilmann.com\" target=\"_blank\">Klasmann</a>.",
  "about.martin.alt": "Martin Löffel, Geschäftsführer",
  "about.martin.position": "Geschäftsführer &amp; Verkauf",
  "about.telja.alt": "Telja Baumann, Administration",
  "about.telja.position": "Administration &amp; Verkauf",
  "about.pascal.alt": "Pascal Probst, Verkauf und Logistik",
  "about.pascal.position": "Verkauf &amp; Logistik",
  "about.sandro.alt": "Sandro Löffel, Warendispo",
  "about.sandro.position": "Warendispo &amp; Stv. Betriebsleiter",
  "about.ivan.alt": "Ivan Gross, Betriebsleiter Gewächshaus",
  "about.ivan.position": "Leiter Gewächshaus",
  "about.shpend.alt": "Shpend Thaqi, Leiter Produktionsanlage",
  "about.shpend.position": "Leiter Produktionsanlage",
  "about.andrzej.alt": "Andrzej Mojsym, Mechaniker und Chauffeur",
  "about.andrzej.position": "Mechaniker &amp; Chauffeur",
  "about.hans-peter.alt": "Hans-Peter Schwab, Chauffeur",
  "about.hans-peter.position": "Interner Transport &amp; Chauffeur",
  "about.damian.alt": "Damian Makarewicz, Stv. Leiter Produktionsanlage",
  "about.damian.position": "Stv. Leiter Produktionsanlage",
  "about.mariusz.alt": "Mariusz Wronski, Interner Transport",
  "about.mariusz.position": "Interner Transport",
  "about.barbara.alt": "Barbara Dubler, Interner Transport",
  "about.barbara.position": "Interner Transport",
  "about.krzysztof.alt": "Mariusz Wronski, Maschinenführer",
  "about.krzysztof.position": "Maschinenführer",

  "portfolio.meta.title": "SwissPlant GmbH &ndash; Angebot",
  "portfolio.meta.description": "Schauen Sie sich unser Angebot an. Wir bieten Warmhauspflanzen verschiedener Sorten an.",
  "portfolio.meta.keywords": "salat, sellerie, kohl, zucchini, tomaten, gurken, lauch, fenchel, setzlinge, warmhauspflanzen, steinwolle, erde, jungpflanzen, angebot, swissplant, agriplant",
  "portfolio.table.1x1": "3cm-Topf",
  "portfolio.table.1x2": "Buntsalate und Sellerie",
  "portfolio.table.2x1": "4cm-Einzeltopf",
  "portfolio.table.2x2": "Buntsalate, Kohlarten und Sellerie",
  "portfolio.table.3x1": "4cm-Riegeltopf",
  "portfolio.table.3x2": "Buntsalate, Kohlarten und Sellerie",
  "portfolio.table.4x1": "6cm-Erdtopf",
  "portfolio.table.4x2": "Zucchini",
  "portfolio.table.5x1": "8cm-Erdtopf",
  "portfolio.table.5x2": "Tomaten, Gurken und Zucchini für den Hobbybereich",
  "portfolio.table.6x1": "Superseeding",
  "portfolio.table.6x2": "Lauch und Fenchel",
  "portfolio.table.7x1": "G195",
  "portfolio.table.7x2": "Kohlarten und Sellerie",
  "portfolio.table.8x1": "G280",
  "portfolio.table.8x2": "Kohlarten und Sellerie",
  "portfolio.description": "Wir bieten Ihnen Warmhauspflanzen in verschiedenen Varianten an. Beispielsweise veredelte und unveredelte Pflanzen oder Pflanzen in Steinwolle oder Erde. Über unser reichhaltiges Jungpflanzensortiment informieren wir Sie gerne. Für kundenspezifische Auskünfte oder Fragen steht Ihnen <a href=\"./ueber-uns.html\">unser Verkaufspersonal</a> jederzeit zur Verfügung.",

  "partners.meta.title": "SwissPlant GmbH &ndash; Partner",
  "partners.meta.description": "Wir arbeiten Hand in Hand mit unseren Partnern. Erfahren Sie mehr über unsere Kooperationen.",
  "partners.meta.keywords": "partner, geschäftspartner, partnerfirmen, partnerfirma, agriplant, agriplant ag, gipmans, gipmans holland, swissplant, kundschaft, spedition, wissen, können, innovationen, qualität",
  "partners.agriplant": "AgriPlant AG",
  "partners.agriplant.description.first": "Durch unseren ortsansässigen Produktionsbetrieb wachsen unsere Jungpflanzen im selben «Haus», wo sie anschliessend weiter kultiviert werden. Dank der individuellen Ausliefertage und den kurzen Transportdistanzen zum Kunden, können wir Ihnen stressfreie Pflanzen anbieten.",
  "partners.agriplant.description.second": "Um alle Wünsche und Bedürfnisse der Kundschaft zu erfüllen, stehen verschiedene Kulturräume zur Verfügung. Der Betrieb ist in der Lage Jungpflanzen von Auberginen bis Zwiebeln bestens zu kultivieren. Die Gewächshäuser entsprechen den neusten technischen Erkenntnissen im Gewächshausbau. Freilandflächen und Cabrio-Häuser zum Abhärten der Pflanzen garantieren optimale Startbedingungen nach dem Pflanzen.",
  "partners.gipmans": "Gipmans Holland",
  "partners.gipmans.description.first": "Bei der Firma <a href=\"http://gipmans.nl\" target=\"_blank\">Gipmans</a> in Holland lassen wir unsere Speedy- und Warmhauspflanzen aussäen. Traypflanzen werden halbfertig bezogen, um sie anschliessend bei uns fertig zu kultivieren. Warmhauspflanzen werden fertig zu uns geliefert und durch unsere eigene Betriebsspedition direkt zum Kunden geliefert.",
  "partners.gipmans.description.second": "Die Firma Gipmans steht für eine marktorientiertes Wissen und Können. Gemeinsame Wissensentwicklungen und Innovationen führen nicht nur zu einem besseren Ertrag, sondern tragen auch dazu bei, dass wir uns weitaus besser auf Ihre jeweils spezifische Marktsituation und die gewünschte Qualität einstellen können.",

  "contact.meta.title": "SwissPlant GmbH &ndash; Kontakt",
  "contact.meta.description": "Erfahren Sie, wie Sie am schnellsten zu uns finden oder uns am einfachsten erreichen.",
  "contact.meta.keywords": "kontakt, mail, email, telefon, bern, neuenburg, neuchatel, kerzers, müntschemier, muentschemier, ins, auto, autobahn, ankunft, anfahrt, swissplant, agriplant",
  "contact.from.bern": "Von Bern her",
  "contact.from.bern.description": "Autobahn Bern–Neuenburg Ausfahrt Kerzers anschliessend Richtung Neuenburg. In Müntschemier Richtung Bahnhof. Firmenwegweiser beachten.",
  "contact.from.neuchatel": "Von Neuchâtel her",
  "contact.from.neuchatel.description": "Richtung Ins–Müntschemier anschliessend in Müntschemier Richtung Bahnhof. Firmenwegweiser beachten.",
  "contact.map": "Karte",

  "common.logo.swissplant.alt": "Logo der SwissPlant GmbH",
  "common.logo.agriplant.alt": "Logo der AgriPlant AG",

  "footer.address": "Spitzallmendweg 11c<br>CH-3225 Müntschemier",
  "footer.phone": "<a href=\"tel:+41323135210\">+41 32 313 52 10</a>",
  "footer.hours": "Montag bis Freitag<br>07:30&ndash;11:45 Uhr<br>13:30&ndash;17:30 Uhr",
  "footer.emails": "<a href=\"mailto:info@swissplant.ch\">info@swissplant.ch</a><br><a href=\"mailto:info@agriplant.ch\">info@agriplant.ch</a>",
  "footer.robin": "Entwickelt und gestaltet von <a href=\"https://robinloeffel.ch\" target=\"_blank\">Robin Löffel</a>",
  "footer.copyright": "&copy; SwissPlant GmbH 2019"
};

export const english = {
  "nav.about": "About us",
  "nav.portfolio": "Portfolio",
  "nav.partners": "Partners",
  "nav.contact": "Contact",
  "nav.start": "Start",

  "home.meta.title": "SwissPlant Ltd. &ndash; Your specialist for vegetable seedings",
  "home.meta.description": "SwissPlant is your go-to specialist for the professional cultivation of vegetables in the Bernese Seeland. We offer warm house plants in many variations.",
  "home.meta.keywords": "vegetables, veggies, seeds, seedings, salad, warm house, plants, warm house plants, swiss, switzerland, bern, seeland, muentschemier, müntschemier, swissplant, agriplant",
  "home.about.heading": "Who we are",
  "home.about.intro": "SwissPlant is the official point of selling of seedings and saplings from AgriPlant Switzerland and Gipmans Netherlands.",
  "home.portfolio.heading": "What we offer",
  "home.portfolio.intro": "Our production site (AgriPlant) is placed in the Bernese Seeland. Our central location makes it possible for us to deliver as fast and as competent as possible.",
  "home.partners.heading": "Who we work with",
  "home.partners.intro": "Gipmans Netherlands provides us with warm house and speedy plants as an addition to our existing product line.",
  "home.contact.heading": "How to contact us",
  "home.contact.intro": "Of course we stand by your side if you need more information or want some tips and tricks.",
  "home.button.more": "Find out more",

  "about.meta.title": "SwissPlant Ltd. &ndash; About us",
  "about.meta.description": "Get to know our firm, SwissPlant, and get a look behind the scenes.",
  "about.meta.keywords": "about us, beginning, history, müntschemier, martin löffel, companies, company, production, muentschemier, swissplant, agriplant, employees, workers, suppliers",
  "about.copy.first": "In the beginning, all these vegetables and salads are seedings, which come directly from AgriPlant here in Müntschemier. CEO and founder of both of our companies, SwissPlant Ltd. and AgriPlant Corp., is Martin Löffel. He summarizes the process from the seedings growing to plants like this: \"We grow the seedings and then supply the cultivation firms with saplings. These then get planted out in the fields.\"",
  "about.copy.second": "The tranding company (SwissPlant) offers vegetables in all possible variations and sizes. Through years of experience, whe can guarantee competent and specific consultings for our climatic circumstances. Our product line is based around products of different breeding programs from worldwide leading companies.",
  "about.copy.third": "Our suppliers are <a href=\"http://bejo.com\" target=\"_blank\">Bejo</a>, <a href=\"http://enzazaden.com\" target=\"_blank\">Enza</a>, <a href=\"http://rijkzwaan.com\" target=\"_blank\">Rijk Zwaan</a>, <a href=\"http://hildsamen.de/eng_ueber_uns.htm\" target=\"_blank\">Hild</a>, <a href=\"http://syngenta.com\" target=\"_blank\">Syngenta</a> and <a href=\"http://www.sakata.com/\" target=\"_blank\">Sakata</a>. We obtain the soild we're using from <a href=\"http://floragard.de/en/\" target=\"_blank\">Floragard</a> and <a href=\"http://www.klasmann-deilmann.com/en/\" target=\"_blank\">Klasmann</a>.",
  "about.martin.alt": "Martin Löffel, CEO",
  "about.martin.position": "CEO &amp; Sales",
  "about.telja.alt": "Telja Baumann, Administration",
  "about.telja.position": "Administration &amp; Sales",
  "about.pascal.alt": "Pascal Probst, Sales and Logistics",
  "about.pascal.position": "Sales &amp; Logistics",
  "about.sandro.alt": "Sandro Löffel, Dispatcher",
  "about.sandro.position": "Dispatcher &amp; Vice CEO",
  "about.ivan.alt": "Ivan Gross, Chief of Greenhouse",
  "about.ivan.position": "Chief of Greenhouse",
  "about.shpend.alt": "Shpend Thaqi, Chief Production Plant",
  "about.shpend.position": "Chief of Production Plant",
  "about.andrzej.alt": "Andrzej Mojsym, Mechanic and Chauffeur",
  "about.andrzej.position": "Mechanic &amp; Chauffeur",
  "about.hans-peter.alt": "Hans-Peter Schwab, Chauffeur",
  "about.hans-peter.position": "Internal Transport &amp; Chauffeur",
  "about.damian.alt": "Damian Makarewicz, Vice Chief of Production Plant",
  "about.damian.position": "Vice Chief of Production Plant",
  "about.mariusz.alt": "Mariusz Wronski, Internal Transport",
  "about.mariusz.position": "Internal Transport",
  "about.barbara.alt": "Barbara Dubler, Internal Transport",
  "about.barbara.position": "Internal Transport",
  "about.krzysztof.alt": "Mariusz Wronski, Chief of Machinery",
  "about.krzysztof.position": "Chief of Machinery",

  "portfolio.meta.title": "SwissPlant Ltd. &ndash; Portfolio",
  "portfolio.meta.description": "This is our portfolio. We offer a wide range of warm house plants and individual consultings.",
  "portfolio.meta.keywords": "salad, salads, celery, cabbage, cabbages, zucchini, tomato, tomatoes, cucumber, cucumbers, leek, fennel, warm house, plants, warm house plants, mineral wool, soil, sales, swissplant, agriplant, portfolio",
  "portfolio.table.1x1": "3cm pot",
  "portfolio.table.1x2": "Salads and celery",
  "portfolio.table.2x1": "4cm single pot",
  "portfolio.table.2x2": "Salads, cabbages and celery",
  "portfolio.table.3x1": "4cm pot",
  "portfolio.table.3x2": "Salads, cabbages and celery",
  "portfolio.table.4x1": "6cm soil pot",
  "portfolio.table.4x2": "Zucchini",
  "portfolio.table.5x1": "8cm soil pot",
  "portfolio.table.5x2": "Tomatoes, cucumbers and zucchini for hobbyists",
  "portfolio.table.6x1": "Superseeding",
  "portfolio.table.6x2": "Leek and fennel",
  "portfolio.table.7x1": "G195",
  "portfolio.table.7x2": "Cabbages and celery",
  "portfolio.table.8x1": "G280",
  "portfolio.table.8x2": "Cabbages and celery",
  "portfolio.description": "We offer warm house plants in various variants. For example refined or unrefined plants or plants in mineral wool or soil. If you need any client-specific information or have questions, <a href=\"./ueber-uns.html\">our sales team</a> would be happy to help.",

  "partners.meta.title": "SwissPlant Ltd. &ndash; Partners",
  "partners.meta.description": "We work hand in hand with our partners. Learn more about our cooperations.",
  "partners.meta.keywords": "partners, partner, business partner, business partners, agriplant, gipmans, gipmans netherlands, swissplant, cleints, distribution, transportation, know-how, knowledge, innovations, quality, improvements, cooperations",
  "partners.agriplant": "AgriPlant Corp.",
  "partners.agriplant.description.first": "Since we produce where we sell, all our saplings grow up in the same \"house\" as they will be cultivated in. Thanks to the individual delivery days and short transportation distances to our clients, we can offer stress-free plants.",
  "partners.agriplant.description.second": "To make every wish of our clients come true, there are several different cultivation areas in our house. From a like aspargus to z like zucchini, we're able to cultivate saplings in the best quality. Our growing houses are updated with the latest technical improvements, and free field areas as well as convertible roof houses allow us to harden the plants before delivering them to you.",
  "partners.gipmans": "Gipmans Netherlands",
  "partners.gipmans.description.first": "At <a href=\"http://gipmans.nl\" target=\"_blank\">Gipmans</a> in the Netherlands, we seed our speedy and warm house saplings. Tray plants are obtained half-finished, so we can then cultivate them in our own house. The warm house plants are delivered to us already finished. They get delivered to our clients through our transportation units.",
  "partners.gipmans.description.second": "Gipmans stands for market-oriented knowledge and know-how. Joint knowledge improvements and innovations lead not only to a greater gain, but let us also help us adapt to your specific market situation and desired quality.",

  "contact.meta.title": "SwissPlant Ltd. &ndash; Contact",
  "contact.meta.description": "Learn how to best get in touch with us. Or get directions to get to our site.",
  "contact.meta.keywords": "contact, mail, email, phone, bern, neuenburg, neuchatel, kerzers, müntschemier, muentschemier, ins, car, freeway, arrival, train, train station",
  "contact.from.bern": "Coming from Bern",
  "contact.from.bern.description": "Highway Bern–Neuchâtel, take the exit to Kerzers and then towards Neuchâtel. In Müntschemier, go in the direction of the train station. Once you're there, take a left and you should see us.",
  "contact.from.neuchatel": "Coming from Neuchâtel",
  "contact.from.neuchatel.description": "Go towards Ins. After Ins, keep that direction. In Müntschemier, go in the direction of the train station. Once you're there, take a left and you should see us.",
  "contact.map": "Map",

  "common.logo.swissplant.alt": "Logo of SwissPlant Ltd.",
  "common.logo.agriplant.alt": "Logo of AgriPlant Corp.",

  "footer.address": "Spitzallmendweg 11c<br/>CH-3225 Müntschemier",
  "footer.phone": "<a href=\"tel:+41323135210\">+41 32 313 52 10</a>",
  "footer.hours": "Mondays to Fridays<br/>07:30&ndash;11:45<br/>13:30&ndash;17:30",
  "footer.emails": "<a href=\"mailto:info@swissplant.ch\">info@swissplant.ch</a><br/><a href=\"mailto:info@agriplant.ch\">info@agriplant.ch</a>",
  "footer.robin": "Developed and designed by <a href=\"https://robinloeffel.ch\" target=\"_blank\">Robin Löffel</a>",
  "footer.copyright": "&copy; SwissPlant Ltd. 2019"
};
