/* eslint-disable */

export const german = {
  "nav.company": "Firma",
  "nav.team": "Team",
  "nav.portfolio": "Angebot",
  "nav.partners": "Partner",
  "nav.contact": "Kontakt",
  "nav.start": "Start",

  "home.meta.title": "SwissPlant GmbH – Ihr Spezialist für Gemüsejungpflanzen",
  "home.meta.description": "Die Swissplant GmbH ist Ihr Ansprechpartner für professionellen Gemüseanbau im Berner Seeland. Bei uns bekommen Sie Warmhauspflanzen in verschiedenen Varianten.",
  "home.meta.keywords": "gemüse, gemuese, jungpflanzen, setzlinge, salat, schweiz, seeland, müntschemier, muentschemier, swissplant, agriplant, swissplant gmbh, agriplant ag, anbau, warmhauspflanzen, distro",
  "home.about.heading": "Wer wir sind",
  "home.about.intro": "Die Firma SwissPlant GmbH ist Verkaufsstelle für Gemüsejungpflanzen der Firmen AgriPlant AG Schweiz und Gipmans Holland.",
  "home.portfolio.heading": "Was wir Ihnen bieten",
  "home.portfolio.intro": "Unser Produktionsstandort der Firma AgriPlant AG befindet sich im Berner Seeland. Die zentrale Lage der Firma bietet uns die Möglichkeit Sie schnell und kompetent zu beliefern.",
  "home.partners.heading": "Mit wem wir arbeiten",
  "home.partners.intro": "Die Firma Gipmans aus Holland beliefert uns als Sortimentsergänzung mit Warmhaus- und Speedypflanzen.",
  "home.contact.heading": "Wie Sie uns erreichen",
  "home.contact.intro": "Wir stehen natürlich gerne für allfällige Informationen und Ratschläge zur Verfügung. Egal, ob E-Mail, Telefon oder vor Ort.",
  "home.button.more": "Mehr erfahren",

  "company.meta.title": "SwissPlant GmbH – Firma",
  "company.meta.description": "Informieren Sie sich darüber, wie die SwissPlant GmbH funktioniert.",
  "company.meta.keywords": "über uns, anfang, geschichte, müntschemier, erfahrung, gemüsebau, kompetent, muentschemier, swissplant, agriplant, swissplant gmbh, agriplant ag",
  "company.copy.first": "Den Anfang nehmen all diese Gemüse und Salate als Jungpflanzen, die von der Firma AgriPlant AG in Müntschemier angezogen werden. Geschäftsführer unserer Firmen Martin Löffel, fasst den Weg der Keimlinge bis hin zu ausgewachsenen Pflanzen so zusammen: &laquo;Wir stehen als Zulieferbetrieb der Gemüsebaubetriebe am Anfang der Produktionskette und kultivieren die Jungpflanzen, die anschliessend von den Gemüsegärtnern gepflanzt werden.&raquo;",
  "company.copy.second": "Die Handelsfirma SwissPlant GmbH, bietet Ihnen Gemüsejungpflanzen in allen möglichen Variationen und Grössen an. Durch unsere jahrelange Erfahrung im Gemüsebau können wir Ihnen eine kompetente und fachspezifische Beratung für unsere klimatischen Bedingungen garantieren. <a href=\"./angebot.html\">Unser Sortiment</a> ist eine Zusammenstellung aus verschiedenen Züchtungsprogrammen der weltweit tätigen Anbieter von Hochleistungssaatgut.",
  "company.copy.third": "Die AgriPlant AG erweiterte im Jahre 2016 ihre Betriebsfläche um 8'130km² auf insgesamt 42'000km². Mit dieser Erweiterung stiess die bestehende Heizölanlage an ihre Grenzen. Darum steht eine neue Zentrale mit Holzhackschnitzelheizung im Bau. Durch die Realisierung dieses Projektes kann die AgriPlant AG ihren CO₂-Ausstoss trotz dem Ausbau um satte 123 Tonnen reduzieren! Mittlerweile ist das Unternehmen zu 80% CO₂-neutral.",
  "company.copy.fourth": "Zu unseren Zulieferfirmen im Bereich Saatgut gehören: <a href=\"http://bejosamen.de\">Bejo</a>, <a href=\"http://enzazaden.de\">Enza</a>, <a href=\"http://rijkzwaan.de\">Rijk Zwaan</a>, <a href=\"http://hildsamen.de/ueber_uns.htm\">Hild</a>, <a href=\"http://syngenta.ch\">Syngenta</a> und <a href=\"http://www.sakata.com\">Sakata</a>. Unsere Anzuchterde beziehen wir bei den Firmen <a href=\"http://floragard.de\">Floragard</a> und <a href=\"http://klasmann-deilmann.com\">Klasmann</a>.",

  "team.meta.title": "SwissPlant GmbH – Team",
  "team.meta.description": "Erfahren Sie, wer bei der SwissPlant GmbH angestellt ist.",
  "team.meta.keywords": "mitarbeiter, angestellte, sales, kontaktdaten, muentschemier, müntschemier, swissplant, agriplant, swissplant gmbh, agriplant ag",
  "team.martin.alt": "Martin Löffel, Geschäftsführer",
  "team.martin.position": "Geschäftsführer &amp; Verkauf",
  "team.telja.alt": "Telja Baumann, Administration",
  "team.telja.position": "Administration &amp; Verkauf",
  "team.pascal.alt": "Pascal Probst, Verkauf und Logistik",
  "team.pascal.position": "Verkauf &amp; Logistik",
  "team.sandro.alt": "Sandro Löffel, Warendispo",
  "team.sandro.position": "Warendispo &amp; Stv. Betriebsleiter",
  "team.ivan.alt": "Ivan Gross, Betriebsleiter Gewächshaus",
  "team.ivan.position": "Leiter Gewächshaus",
  "team.shpend.alt": "Shpend Thaqi, Leiter Produktionsanlage",
  "team.shpend.position": "Leiter Produktionsanlage",
  "team.andrzej.alt": "Andrzej Mojsym, Mechaniker und Chauffeur",
  "team.andrzej.position": "Mechaniker &amp; Chauffeur",
  "team.hans-peter.alt": "Hans-Peter Schwab, Chauffeur",
  "team.hans-peter.position": "Interner Transport &amp; Chauffeur",
  "team.damian.alt": "Damian Makarewicz, Stv. Leiter Produktionsanlage",
  "team.damian.position": "Stv. Leiter Produktionsanlage",
  "team.mariusz.alt": "Mariusz Wronski, Interner Transport",
  "team.mariusz.position": "Interner Transport",
  "team.barbara.alt": "Barbara Dubler, Interner Transport",
  "team.barbara.position": "Interner Transport",
  "team.krzysztof.alt": "Mariusz Wronski, Maschinenführer",
  "team.krzysztof.position": "Maschinenführer",

  "portfolio.meta.title": "SwissPlant GmbH – Angebot",
  "portfolio.meta.description": "Schauen Sie sich unser Angebot an. Wir bieten Warmhauspflanzen verschiedener Sorten an.",
  "portfolio.meta.keywords": "salat, sellerie, kohl, zucchini, tomaten, gurken, lauch, fenchel, setzlinge, warmhauspflanzen, steinwolle, erde, jungpflanzen, angebot, swissplant, agriplant",
  "portfolio.table.1x1": "3.2cm-Einzeltopf",
  "portfolio.table.1x2": "Buntsalate, Nüssler, Sellerie und Lauch",
  "portfolio.table.10x1": "3.2cm-Doppeltopf",
  "portfolio.table.10x2": "Buntsalate, Nüssler, Sellerie und Lauch",
  "portfolio.table.11x1": "3.7cm-Einzeltopf",
  "portfolio.table.11x2": "Buntsalate, Nüssler, Sellerie und Lauch",
  "portfolio.table.12x1": "3.7cm-Riegeltopf",
  "portfolio.table.12x2": "Buntsalate, Sellerie und Lauch",
  "portfolio.table.2x1": "4cm-Einzeltopf",
  "portfolio.table.2x2": "Buntsalate, Nüssler, Sellerie und Lauch",
  "portfolio.table.3x1": "4cm-Riegeltopf",
  "portfolio.table.3x2": "Buntsalate, Sellerie und Lauch",
  "portfolio.table.13x1": "5cm-Einzeltopf",
  "portfolio.table.13x2": "Buntsalate",
  "portfolio.table.4x1": "6cm-Geklebt",
  "portfolio.table.4x2": "Zucchetti",
  "portfolio.table.6x1": "Superseedling",
  "portfolio.table.6x2": "Lauch und Fenchel",
  "portfolio.table.7x1": "G195",
  "portfolio.table.7x2": "Kohlarten und Sellerie",
  "portfolio.table.8x1": "G280",
  "portfolio.table.8x2": "Kohlarten und Sellerie",
  "portfolio.table.9x1": "PT770",
  "portfolio.table.9x2": "Lauch- und Kohlarten",
  "portfolio.table.14x1": "TQ 10.5",
  "portfolio.table.14x2": "Warmhauspflanzen Hobbybereich unveredelt",
  "portfolio.description": "Alle Topfvarianten (3.2cm–6cm) werden in unserem Haus produziert, die übrigen Arten lassen wir von <a href=\"./partner.html\">unseren holländischen Partnern</a> herstellen. Wir bieten auch Warmhauspflanzen in verschiedenen Varianten an. Über unser reichhaltiges Jungpflanzensortiment informieren wir Sie gerne. Für kundenspezifische Auskünfte oder Fragen steht Ihnen <a href=\"./team.html\">unser Verkaufspersonal</a> jederzeit zur Verfügung.",

  "partners.meta.title": "SwissPlant GmbH – Partner",
  "partners.meta.description": "Wir arbeiten Hand in Hand mit unseren Partnern. Erfahren Sie mehr über unsere Kooperationen.",
  "partners.meta.keywords": "partner, geschäftspartner, partnerfirmen, partnerfirma, agriplant, agriplant ag, gipmans, gipmans holland, swissplant, kundschaft, spedition, wissen, können, innovationen, qualität",
  "partners.agriplant": "AgriPlant AG",
  "partners.agriplant.description.first": "Durch unseren ortsansässigen Produktionsbetrieb wachsen unsere Jungpflanzen im selben «Haus», wo sie anschliessend weiter kultiviert werden. Dank der individuellen Ausliefertage und den kurzen Transportdistanzen zum Kunden, können wir Ihnen stressfreie Pflanzen anbieten.",
  "partners.agriplant.description.second": "Um alle Wünsche und Bedürfnisse der Kundschaft zu erfüllen, stehen verschiedene Kulturräume zur Verfügung. Der Betrieb ist in der Lage Jungpflanzen von Auberginen bis Zwiebeln bestens zu kultivieren. Die Gewächshäuser entsprechen den neusten technischen Erkenntnissen im Gewächshausbau. Freilandflächen und Cabrio-Häuser zum Abhärten der Pflanzen garantieren optimale Startbedingungen nach dem Pflanzen.",
  "partners.gipmans": "Gipmans Holland",
  "partners.gipmans.description.first": "Bei der Firma <a href=\"http://gipmans.nl\">Gipmans</a> in Holland lassen wir unsere Speedy- und Warmhauspflanzen aussäen. Traypflanzen werden halbfertig bezogen, um sie anschliessend bei uns fertig zu kultivieren. Warmhauspflanzen werden fertig zu uns geliefert und durch unsere eigene Betriebsspedition direkt zum Kunden geliefert.",
  "partners.gipmans.description.second": "Die Firma Gipmans steht für eine marktorientiertes Wissen und Können. Gemeinsame Wissensentwicklungen und Innovationen führen nicht nur zu einem besseren Ertrag, sondern tragen auch dazu bei, dass wir uns weitaus besser auf Ihre jeweils spezifische Marktsituation und die gewünschte Qualität einstellen können.",

  "contact.meta.title": "SwissPlant GmbH – Kontakt",
  "contact.meta.description": "Erfahren Sie, wie Sie am schnellsten zu uns finden oder uns am einfachsten erreichen.",
  "contact.meta.keywords": "kontakt, mail, email, telefon, bern, neuenburg, neuchatel, kerzers, müntschemier, muentschemier, ins, auto, autobahn, ankunft, anfahrt, swissplant, agriplant",
  "contact.from.bern": "Von Bern her",
  "contact.from.bern.description": "Autobahn Bern–Neuenburg Ausfahrt Kerzers anschliessend Richtung Neuenburg. In Müntschemier Richtung Bahnhof. Firmenwegweiser beachten.",
  "contact.from.neuchatel": "Von Neuchâtel her",
  "contact.from.neuchatel.description": "Richtung Ins–Müntschemier anschliessend in Müntschemier Richtung Bahnhof. Firmenwegweiser beachten.",
  "contact.map": "Karte",

  "common.logo.swissplant.alt": "Logo der SwissPlant GmbH",
  "common.logo.agriplant.alt": "Logo der AgriPlant AG",

  "footer.address": "Spitzallmendweg 11c<br>CH-3225 Müntschemier",
  "footer.phone": "<a href=\"tel:+41323135210\">+41 32 313 52 10</a>",
  "footer.hours": "Montag bis Freitag<br>07:30–11:45 Uhr<br>13:30–17:30 Uhr",
  "footer.emails": "<a href=\"mailto:info@swissplant.ch\">info@swissplant.ch</a><br><a href=\"mailto:info@agriplant.ch\">info@agriplant.ch</a>",
  "footer.robin": "Entwickelt und gestaltet von <a href=\"https://robinloeffel.ch\">Robin Löffel</a>",
  "footer.copyright": "&copy; SwissPlant GmbH 2019"
};

export const english = {
  "nav.company": "Company",
  "nav.team": "Team",
  "nav.portfolio": "Portfolio",
  "nav.partners": "Partners",
  "nav.contact": "Contact",
  "nav.start": "Start",

  "home.meta.title": "SwissPlant Ltd. – Your specialist for vegetable seedings",
  "home.meta.description": "SwissPlant is your go-to specialist for the professional cultivation of vegetables in the Bernese Seeland. We offer warm house plants in many variations.",
  "home.meta.keywords": "vegetables, veggies, seeds, seedings, salad, warm house, plants, warm house plants, swiss, switzerland, bern, seeland, muentschemier, müntschemier, swissplant, agriplant",
  "home.about.heading": "Who we are",
  "home.about.intro": "SwissPlant is the official point of selling of seedings and saplings from AgriPlant Switzerland and Gipmans Netherlands.",
  "home.portfolio.heading": "What we offer",
  "home.portfolio.intro": "Our production site (AgriPlant) is placed in the Bernese Seeland. Our central location makes it possible for us to deliver as fast and as competent as possible.",
  "home.partners.heading": "Who we work with",
  "home.partners.intro": "Gipmans Netherlands provides us with warm house and speedy plants as an addition to our existing product line.",
  "home.contact.heading": "How to contact us",
  "home.contact.intro": "Of course we stand by your side if you need more information or want some tips and tricks.",
  "home.button.more": "Find out more",

  "company.meta.title": "SwissPlant Ltd. – About us",
  "company.meta.description": "Get to know our firm, SwissPlant, and get a look behind the scenes.",
  "company.meta.keywords": "company.us, beginning, history, müntschemier, martin löffel, companies, company, production, muentschemier, swissplant, agriplant, employees, workers, suppliers",
  "company.copy.first": "In the beginning, all these vegetables and salads are seedings, which come directly from AgriPlant here in Müntschemier. CEO and founder of both of our companies, SwissPlant Ltd. and AgriPlant Corp., is Martin Löffel. He summarizes the process from the seedings growing to plants like this: \"We grow the seedings and then supply the cultivation firms with saplings. These then get planted out in the fields.\"",
  "company.copy.second": "The tranding company (SwissPlant) offers vegetables in all possible variations and sizes. Through years of experience, whe can guarantee competent and specific consultings for our climatic circumstances. Our product line is based around products of different breeding programs from worldwide leading companies.",
  "company.copy.third": "In 2016, AgriPlant expanded its production area by 8,130 km² to a total of 42,000 km². This expansion pushed the existing heating oil plant to its limits. Therefore, a new central plant with wood chip heating is under construction. By implementing this project, AgriPlant can reduce its CO₂ output by a massive 123 tonnes despite the expansion! The company is now 80% CO₂-neutral.",
  "company.copy.fourth": "Our suppliers are <a href=\"http://bejo.com\">Bejo</a>, <a href=\"http://enzazaden.com\">Enza</a>, <a href=\"http://rijkzwaan.com\">Rijk Zwaan</a>, <a href=\"http://hildsamen.de/eng_ueber_uns.htm\">Hild</a>, <a href=\"http://syngenta.com\">Syngenta</a> and <a href=\"http://www.sakata.com/\">Sakata</a>. We obtain the soild we're using from <a href=\"http://floragard.de/en/\">Floragard</a> and <a href=\"http://www.klasmann-deilmann.com/en/\">Klasmann</a>.",

  "team.meta.title": "SwissPlant GmbH – Team",
  "team.meta.description": "Find out who works for SwissPlant.",
  "team.meta.keywords": "employees, co-workers, sales, contact data, muentschemier, müntschemier, swissplant, agriplant, swissplant gmbh, agriplant ag",
  "team.martin.alt": "Martin Löffel, CEO",
  "team.martin.position": "CEO &amp; Sales",
  "team.telja.alt": "Telja Baumann, Administration",
  "team.telja.position": "Administration &amp; Sales",
  "team.pascal.alt": "Pascal Probst, Sales and Logistics",
  "team.pascal.position": "Sales &amp; Logistics",
  "team.sandro.alt": "Sandro Löffel, Dispatcher",
  "team.sandro.position": "Dispatcher &amp; Vice CEO",
  "team.ivan.alt": "Ivan Gross, Chief of Greenhouse",
  "team.ivan.position": "Chief of Greenhouse",
  "team.shpend.alt": "Shpend Thaqi, Chief Production Plant",
  "team.shpend.position": "Chief of Production Plant",
  "team.andrzej.alt": "Andrzej Mojsym, Mechanic and Chauffeur",
  "team.andrzej.position": "Mechanic &amp; Chauffeur",
  "team.hans-peter.alt": "Hans-Peter Schwab, Chauffeur",
  "team.hans-peter.position": "Internal Transport &amp; Chauffeur",
  "team.damian.alt": "Damian Makarewicz, Vice Chief of Production Plant",
  "team.damian.position": "Vice Chief of Production Plant",
  "team.mariusz.alt": "Mariusz Wronski, Internal Transport",
  "team.mariusz.position": "Internal Transport",
  "team.barbara.alt": "Barbara Dubler, Internal Transport",
  "team.barbara.position": "Internal Transport",
  "team.krzysztof.alt": "Mariusz Wronski, Chief of Machinery",
  "team.krzysztof.position": "Chief of Machinery",

  "portfolio.meta.title": "SwissPlant Ltd. – Portfolio",
  "portfolio.meta.description": "This is our portfolio. We offer a wide range of warm house plants and individual consultings.",
  "portfolio.meta.keywords": "salad, salads, celery, cabbage, cabbages, zucchini, tomato, tomatoes, cucumber, cucumbers, leek, fennel, warm house, plants, warm house plants, mineral wool, soil, sales, swissplant, agriplant, portfolio",
  "portfolio.table.1x1": "3.2cm single pot",
  "portfolio.table.1x2": "Salads, field salad, celery and leek",
  "portfolio.table.10x1": "3.2cm double pot",
  "portfolio.table.10x2": "Salads, field salad, celery and leek",
  "portfolio.table.11x1": "3.7cm single pot",
  "portfolio.table.11x2": "Salads, field salad, celery and leek",
  "portfolio.table.12x1": "3.7cm lock pot",
  "portfolio.table.12x2": "Salads, celery and leek",
  "portfolio.table.2x1": "4cm single pot",
  "portfolio.table.2x2": "Salads, field salad, celery and leek",
  "portfolio.table.3x1": "4cm lock pot",
  "portfolio.table.3x2": "Salads, celery and leek",
  "portfolio.table.13x1": "5cm single pot",
  "portfolio.table.13x2": "Salads",
  "portfolio.table.4x1": "6cm glued",
  "portfolio.table.4x2": "Zucchini",
  "portfolio.table.6x1": "Superseedling",
  "portfolio.table.6x2": "Leek and fennel",
  "portfolio.table.7x1": "G195",
  "portfolio.table.7x2": "Cabbages and celery",
  "portfolio.table.8x1": "G280",
  "portfolio.table.8x2": "Cabbages and celery",
  "portfolio.table.9x1": "PT770",
  "portfolio.table.9x2": "Leeks and cabbages",
  "portfolio.table.14x1": "TQ 10.5",
  "portfolio.table.14x2": "Warm house plants for hobbyists",
  "portfolio.description": "All pot variants (3.2cm to 6cm) are produced in-house. Everything else is produced by <a href=\"partner.html\">our dutch partners</a>. We also offer warm house plants in various variants. If you need any information or have questions, <a href=\"./team.html\">our sales team</a> will be happy to help you out!",

  "partners.meta.title": "SwissPlant Ltd. – Partners",
  "partners.meta.description": "We work hand in hand with our partners. Learn more about our cooperations.",
  "partners.meta.keywords": "partners, partner, business partner, business partners, agriplant, gipmans, gipmans netherlands, swissplant, cleints, distribution, transportation, know-how, knowledge, innovations, quality, improvements, cooperations",
  "partners.agriplant": "AgriPlant Corp.",
  "partners.agriplant.description.first": "Since we produce where we sell, all our saplings grow up in the same \"house\" as they will be cultivated in. Thanks to the individual delivery days and short transportation distances to our clients, we can offer stress-free plants.",
  "partners.agriplant.description.second": "To make every wish of our clients come true, there are several different cultivation areas in our house. From a like aspargus to z like zucchini, we're able to cultivate saplings in the best quality. Our growing houses are updated with the latest technical improvements, and free field areas as well as convertible roof houses allow us to harden the plants before delivering them to you.",
  "partners.gipmans": "Gipmans Netherlands",
  "partners.gipmans.description.first": "At <a href=\"http://gipmans.nl\">Gipmans</a> in the Netherlands, we seed our speedy and warm house saplings. Tray plants are obtained half-finished, so we can then cultivate them in our own house. The warm house plants are delivered to us already finished. They get delivered to our clients through our transportation units.",
  "partners.gipmans.description.second": "Gipmans stands for market-oriented knowledge and know-how. Joint knowledge improvements and innovations lead not only to a greater gain, but let us also help us adapt to your specific market situation and desired quality.",

  "contact.meta.title": "SwissPlant Ltd. – Contact",
  "contact.meta.description": "Learn how to best get in touch with us. Or get directions to get to our site.",
  "contact.meta.keywords": "contact, mail, email, phone, bern, neuenburg, neuchatel, kerzers, müntschemier, muentschemier, ins, car, freeway, arrival, train, train station",
  "contact.from.bern": "Coming from Bern",
  "contact.from.bern.description": "Highway Bern–Neuchâtel, take the exit to Kerzers and then towards Neuchâtel. In Müntschemier, go in the direction of the train station. Once you're there, take a left and you should see us.",
  "contact.from.neuchatel": "Coming from Neuchâtel",
  "contact.from.neuchatel.description": "Go towards Ins. After Ins, keep that direction. In Müntschemier, go in the direction of the train station. Once you're there, take a left and you should see us.",
  "contact.map": "Map",

  "common.logo.swissplant.alt": "Logo of SwissPlant Ltd.",
  "common.logo.agriplant.alt": "Logo of AgriPlant Corp.",

  "footer.address": "Spitzallmendweg 11c<br/>CH-3225 Müntschemier",
  "footer.phone": "<a href=\"tel:+41323135210\">+41 32 313 52 10</a>",
  "footer.hours": "Mondays to Fridays<br/>07:30–11:45<br/>13:30–17:30",
  "footer.emails": "<a href=\"mailto:info@swissplant.ch\">info@swissplant.ch</a><br/><a href=\"mailto:info@agriplant.ch\">info@agriplant.ch</a>",
  "footer.robin": "Developed and designed by <a href=\"https://robinloeffel.ch\">Robin Löffel</a>",
  "footer.copyright": "&copy; SwissPlant Ltd. 2019"
};
