name: deploy static assets to preview

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: set up pages
        uses: actions/configure-pages@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          check-latest: true

      - name: install node_modules
        run: yarn install

      - name: run build
        run: yarn dist

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
